### ISSUE TITLE
Finished repo for mongoDB controller?

### ISSUE THREAD

**Issue by austinmajor** [DirectXMan12/kubebuilder-workshops#3]
Hello @DirectXMan12 @pwittrock - is there a completed repo for the MongoDB controller implementation? I'm running into several issues and I wanted to diff my project to see what I'm doing wrong.

**Comment by DirectXMan12** [comment]
cc @pwittrock

**Comment by DirectXMan12** [comment]
fixed now -- see https://github.com/DirectXMan12/kubebuilder-workshops/tree/solutions/software-architecture-2019
